[project]
name = "video-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "jinja2>=3.1.4",
    "python-multipart>=0.0.19",
    "uvicorn>=0.32.1",
]
